// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3r_260NiNZ3KBlwLp26A1NQTr1b7RAU',
    appId: '1:299394215184:web:f43a0eb7b5da8f2b808995',
    messagingSenderId: '299394215184',
    projectId: 'renewque-36524',
    authDomain: 'renewque-36524.firebaseapp.com',
    storageBucket: 'renewque-36524.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMCaSm9MTcFf7Fmu0B55IaqSKRn5cEG0',
    appId: '1:299394215184:android:cbcb33c48d50d409808995',
    messagingSenderId: '299394215184',
    projectId: 'renewque-36524',
    storageBucket: 'renewque-36524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGhwE1QKUoYjOqOTCOCLIOatvLlFozKxg',
    appId: '1:299394215184:ios:67433b42b8c5f59e808995',
    messagingSenderId: '299394215184',
    projectId: 'renewque-36524',
    storageBucket: 'renewque-36524.firebasestorage.app',
    iosBundleId: 'com.example.fashionAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGhwE1QKUoYjOqOTCOCLIOatvLlFozKxg',
    appId: '1:299394215184:ios:67433b42b8c5f59e808995',
    messagingSenderId: '299394215184',
    projectId: 'renewque-36524',
    storageBucket: 'renewque-36524.firebasestorage.app',
    iosBundleId: 'com.example.fashionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-3r_260NiNZ3KBlwLp26A1NQTr1b7RAU',
    appId: '1:299394215184:web:1417c4ffa5f0c1fe808995',
    messagingSenderId: '299394215184',
    projectId: 'renewque-36524',
    authDomain: 'renewque-36524.firebaseapp.com',
    storageBucket: 'renewque-36524.firebasestorage.app',
  );
}
